title: Project UAS
description: >
  **I am Strata**, a super simple
  responsive site template freebie
  crafted by [HTML5 UP](http://html5up.net).
copyright: Kami Semua
sass:
  sass_dir: assets/sass
url: https://sifuinsuskariau.github.io/strata.github.io/
# disqus_shortname: stratajekylldemo
# facebook_username:
# twitter_username: "#"
# linkedin_username: "#"
# instagram_username:
# pinterest_username:
# flickr_username:
 github_username:  "https://sifuinsuskariau.github.io"
# feed_icon: rss
#email: "#"
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
